Hubs:
    0:
        rxChannels: [0]
        txChannels: [0]
        attachedNodes: [0,1,4,5]

    1:
        rxChannels: [0]
        txChannels: [0]
        attachedNodes: [2,3,6,7]

    2:
        rxChannels: [0]
        txChannels: [0]
        attachedNodes : [8,9,12,13]

    3:
        rxChannels: [0]
        txChannels: [0]
        attachedNodes: [10,11,14,15]

Channels:
    0:
      # Prop: [RX_value, TX_value]
        ber: [0, 0]
        delay: [0, 0]

#
#  Other configurations
#

# Verbosity levels:
#   VERBOSE_OFF    0
#   VERBOSE_LOW    1
#   VERBOSE_MEDIUM 2
#   VERBOSE_HIGH   3
verbose_mode: 0

# Trace
trace_mode: false
trace_filename: ""

#
# NoC General Configuration
#
mesh_dim_x: 4
mesh_dim_y: 4
buffer_depth: 4
max_packet_size: 10
min_packet_size: 2

# Routing algorithms
#   ROUTING_XY             0
#   ROUTING_WEST_FIRST     1
#   ROUTING_NORTH_LAST     2
#   ROUTING_NEGATIVE_FIRST 3
#   ROUTING_ODD_EVEN       4
#   ROUTING_DYAD           5
#   ROUTING_FULLY_ADAPTIVE 8
#   ROUTING_TABLE_BASED    9
routing_algorithm: 0
routing_table_filename: ""

# Selection Strategies
#   SEL_RANDOM             0
#   SEL_BUFFER_LEVEL       1
#   SEL_NOP                2
selection_strategy: 0

packet_injection_rate: 0.01
probability_of_retransmission: 0.01

# Traffic distribution
#   TRAFFIC_RANDOM         0
#   TRAFFIC_TRANSPOSE1     1
#   TRAFFIC_TRANSPOSE2     2
#   TRAFFIC_HOTSPOT        3
#   TRAFFIC_TABLE_BASED    4
#   TRAFFIC_BIT_REVERSAL   5
#   TRAFFIC_SHUFFLE        6
#   TRAFFIC_BUTTERFLY      7
traffic_distribution: 4
traffic_table_filename: "tt.txt"

reset_time: 1000
simulation_time: 10000
stats_warm_up_time: 1000
detailed: false
dyad_threshold: 0.6
max_volume_to_be_drained: 0
router_power_filename: "default_router.yaml"
low_power_link_strategy: false
qos: 1.0
show_buffer_stats: false
use_winoc: false
