Hubs:
    0:
        rxChannels: [0]
        txChannels: [0]
        attachedNodes: [0,1,4,5]

    1:
        rxChannels: [0]
        txChannels: [0]
        attachedNodes: [2,3,6,7]

    2:
        rxChannels: [0]
        txChannels: [0]
        attachedNodes : [8,9,12,13]

    3:
        rxChannels: [0]
        txChannels: [0]
        attachedNodes: [10,11,14,15]

Channels:
    0:
      # Prop: [RX_value, TX_value]
        BER: [0, 0]
        Delay: [0, 0]
